[package]
name = "appstoreconnect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "8"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.152"
serde_json = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
base64 = "0"
